site_name: ezVIS Documentation
repo_url: https://github.com/madec-project/ezvis/
repo_name: GitHub
theme: ReadTheDocs
site_description: Documentation for ezVIS
docs_dir: doc
include_search: true
pages:
- ['index.md','Home']
- ['Installation.md', 'Installation']
- ['ConfigurationFile.md', 'Configuration', 'Configuration file']
#- ['DocumentFields.md', 'Configuration', 'documentFields']
#- ['CorpusFields.md', 'Configuration', 'corpusFields']
#- ['FlyingFields.md', 'Configuration', 'flyingFields']
#- ['Dashboard.md', 'Configuration', 'Dashboard']
#- ['Histogram.md', 'Configuration', 'histogram']
#- ['HorizontalBars.md', 'Configuration', 'horizontalbars']
#- ['Pie.md', 'Configuration', 'pie']
#- ['Map.md', 'Configuration', 'map']
#- ['Network.md', 'Configuration', 'network']
#- ['Preferences.md', 'Configuration', 'Charts\' preferences']
#- ['Fields.md', 'Configuration', 'Field parameters to charts']
#- ['Operators.md', 'Configuration', 'Operator parameter to charts']
#- ['Flying.md', 'Configuration', 'Flying parameter to charts']
#- ['Facets.md', 'Configuration', 'Facets']
#- ['Documents.md', 'Configuration', 'Documents table']
#- ['Display.md', 'Configuration', 'Document\'s page']
#- ['Pages.md', 'Configuration', 'Pages\' labels and texts']
#- ['Loaders.md', 'Configuration', 'Loaders by format']
#- ['Access.md', 'Configuration', 'Access restriction by login/password']
#- ['JBJ.md', 'JBJ', 'Configuration syntax: JBJ']
