site_name: ezVIS Documentation
repo_url: https://github.com/madec-project/ezvis/
repo_name: GitHub
theme: readthedocs
site_description: Documentation for ezVIS
docs_dir: doc
include_search: true
pages:
- Summary: index.md
- Installation: Installation.md
- Getting Started: GettingStarted.md
- Configuration:
    - JSON file: ConfigurationFile.md
    - corpusFields: CorpusFields.md
    - flyingFields: FlyingFields.md
    - Access restriction by login/password: Access.md
- Dashboard:
    - Dashboard: Dashboard.md
    - histogram: Histogram.md
    - horizontalbars: HorizontalBars.md
    - pie: Pie.md
    - map: Map.md
    - network: Network.md
    - Charts preferences: Preferences.md
    - Facets: Facets.md
- Chart parameters:
    - Field parameteres to charts: Fields.md
    - Operator parameter to charts: Operators.md
    - Flying parameter to charts: Flying.md
- Pages:
    - Documents table: Documents.md
    - Documents page: Display.md
    - Pages labels and texts: Pages.md
- Data:
    - Loaders by format: Loaders.md
- Annexes:
    - JBJ: JBJ.md
    - Showcase: Showcase.md
    - Blog: MADEC.md
    - Thanks: PoweredBy.md
