site_name: ezVIS Documentation
repo_url: https://github.com/madec-project/ezvis/
repo_name: GitHub
theme: ReadTheDocs
site_description: Documentation for ezVIS
docs_dir: doc
include_search: true
pages:
- ['index.md','Home']
- ['Installation.md', 'Installation']
- ['ConfigurationFile.md', 'Configuration', 'JSON file']
- ['DocumentFields.md', 'Configuration', 'documentFields']
- ['CorpusFields.md', 'Configuration', 'corpusFields']
- ['FlyingFields.md', 'Configuration', 'flyingFields']
- ['Access.md', 'Configuration', 'Access restriction by login/password']
- ['Dashboard.md', 'Dashboard', 'Dashboard']
- ['Histogram.md', 'Dashboard', 'histogram']
- ['HorizontalBars.md', 'Dashboard', 'horizontalbars']
- ['Pie.md', 'Dashboard', 'pie']
- ['Map.md', 'Dashboard', 'map']
- ['Network.md', 'Dashboard', 'network']
- ['Preferences.md', 'Dashboard', 'Charts'' preferences']
- ['Facets.md', 'Dashboard', 'Facets']
- ['Fields.md', 'Routes', 'Field parameters to charts']
- ['Operators.md', 'Routes', 'Operator parameter to charts']
- ['Flying.md', 'Routes', 'Flying parameter to charts']
- ['Documents.md', 'Other Pages', 'Documents table']
- ['Display.md', 'Other Pages', 'Document''s page']
- ['Pages.md', 'Other Pages', 'Pages'' labels and texts']
- ['Loaders.md', 'Data', 'Loaders by format']
- ['JBJ.md', 'Annex', 'JBJ']
